import type { Metadata } from "next";
import { Rozha_One } from "next/font/google";
import "./globals.css";

const rozha = Rozha_One({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "My Page",
  description: "Generated by Bruno",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rozha.className}>{children}</body>
    </html>
  );
}
