import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Footer from "../../components/footer/page";
import { HomeButton } from "../../components/homeButton/button";

const inter = Inter_Tight({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "100", "200", "300", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "My Page",
  description: "Generated by Bruno",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body className={inter.className}>
        <main>
          {children}
          <Footer />
          <HomeButton />
        </main>
      </body>
    </html>
  );
}
