import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { i18n, type Locale } from "../../i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const inter = Inter_Tight({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "100", "200", "300", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "My Page",
  description: "Generated by Bruno",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
